package top.daxianwill.mvp.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import top.daxianwill.mvp.entity.WeatherinfoEntity;

import top.daxianwill.mvp.entity.WeatherinfoEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weatherinfoEntityDaoConfig;

    private final WeatherinfoEntityDao weatherinfoEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weatherinfoEntityDaoConfig = daoConfigMap.get(WeatherinfoEntityDao.class).clone();
        weatherinfoEntityDaoConfig.initIdentityScope(type);

        weatherinfoEntityDao = new WeatherinfoEntityDao(weatherinfoEntityDaoConfig, this);

        registerDao(WeatherinfoEntity.class, weatherinfoEntityDao);
    }
    
    public void clear() {
        weatherinfoEntityDaoConfig.clearIdentityScope();
    }

    public WeatherinfoEntityDao getWeatherinfoEntityDao() {
        return weatherinfoEntityDao;
    }

}
